//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EticaretSitemiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class KATEGORI_URUNLER
    {
        public int kategori_urunID { get; set; }
        public Nullable<int> kategoriID { get; set; }
        public Nullable<int> urunID { get; set; }
    
        public virtual KATEGORILER KATEGORILER { get; set; }
        public virtual URUNLER URUNLER { get; set; }
    }
}
