//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EticaretSitemiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class KATEGORILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KATEGORILER()
        {
            this.KATEGORI_URUNLER = new HashSet<KATEGORI_URUNLER>();
        }
    
        public int kategoriID { get; set; }
        public string kategoriAdi { get; set; }
        public Nullable<int> kategoriSira { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KATEGORI_URUNLER> KATEGORI_URUNLER { get; set; }
    }
}
