//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EticaretSitemiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        public int kullaniciID { get; set; }
        public string kullaniciAdi { get; set; }
        public string password { get; set; }
    }
}
