//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EticaretSitemiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class REKLAM
    {
        public int reklamID { get; set; }
        public string reklamAd { get; set; }
        public string reklamKodu { get; set; }
        public Nullable<bool> durum { get; set; }
        public string yer { get; set; }
    }
}
