//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EticaretSitemiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITEAYARLARI
    {
        public int siteAyarlariID { get; set; }
        public string ayarisim { get; set; }
        public string ayardeger { get; set; }
        public Nullable<bool> durum { get; set; }
    }
}
